CREATE TABLE batch_job_execution_seq (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE batch_job_instance (
    job_instance_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version BIGINT,
    job_name VARCHAR(100) NOT NULL,
    job_key VARCHAR(32) NOT NULL,
    UNIQUE (job_name, job_key)
);

CREATE TABLE batch_job_execution (
    job_execution_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version BIGINT,
    job_instance_id BIGINT NOT NULL
        CONSTRAINT job_inst_exec_fk
            REFERENCES batch_job_instance,
    create_time TIMESTAMP NOT NULL,
    start_time TIMESTAMP DEFAULT NULL,
    end_time TIMESTAMP DEFAULT NULL,
    status VARCHAR(10),
    exit_code VARCHAR(2500),
    exit_message VARCHAR(2500),
    last_updated TIMESTAMP,
    job_configuration_location VARCHAR(2500)
);

CREATE TABLE batch_job_execution_context (
    job_execution_id BIGINT NOT NULL PRIMARY KEY
        CONSTRAINT job_exec_ctx_fk
            REFERENCES batch_job_execution,
    short_context VARCHAR(2500) NOT NULL,
    serialized_context VARCHAR(16777216)
);

CREATE TABLE batch_job_execution_params (
    job_execution_id BIGINT NOT NULL
        CONSTRAINT job_exec_params_fk
            REFERENCES batch_job_execution,
    type_cd VARCHAR(6) NOT NULL,
    key_name VARCHAR(100) NOT NULL,
    string_val VARCHAR(250),
    date_val TIMESTAMP DEFAULT NULL,
    long_val BIGINT,
    double_val DOUBLE,
    identifying CHARACTER(1) NOT NULL
);

CREATE TABLE batch_job_seq (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE batch_step_execution (
    step_execution_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version BIGINT NOT NULL,
    step_name VARCHAR(100) NOT NULL,
    job_execution_id BIGINT NOT NULL
        CONSTRAINT job_exec_step_fk
            REFERENCES batch_job_execution,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP DEFAULT NULL,
    status VARCHAR(10),
    commit_count BIGINT,
    read_count BIGINT,
    filter_count BIGINT,
    write_count BIGINT,
    read_skip_count BIGINT,
    write_skip_count BIGINT,
    process_skip_count BIGINT,
    rollback_count BIGINT,
    exit_code VARCHAR(2500),
    exit_message VARCHAR(2500),
    last_updated TIMESTAMP
);

CREATE TABLE batch_step_execution_context (
    step_execution_id BIGINT NOT NULL PRIMARY KEY
        CONSTRAINT step_exec_ctx_fk
            REFERENCES batch_step_execution,
    short_context VARCHAR(2500) NOT NULL,
    serialized_context VARCHAR(16777216)
);

CREATE TABLE batch_step_execution_seq (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE library (
    id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    creation_time TIMESTAMP,
    update_time TIMESTAMP,
    version INTEGER,
    path VARCHAR(255)
);

CREATE TABLE selection_values (
    id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255)
);

CREATE TABLE metadata_options (
    dtype VARCHAR(31) NOT NULL,
    id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    default_number_value INTEGER,
    "MAX" INTEGER,
    "MIN" INTEGER,
    step INTEGER,
    default_date_value DATE,
    default_text_value VARCHAR(255),
    suggest BOOLEAN,
    default_time_value TIME,
    default_timestamp_value TIMESTAMP,
    default_boolean_value BOOLEAN,
    default_long_value BIGINT,
    default_select_value_id BIGINT REFERENCES selection_values,
    default_tag_values VARCHAR(255) ARRAY,
    default_double_value DOUBLE
);

CREATE TABLE metadata (
    id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    ordering VARCHAR(255),
    read_only BOOLEAN NOT NULL,
    system_specified BOOLEAN,
    display_order INTEGER,
    type INTEGER,
    creation_time TIMESTAMP,
    update_time TIMESTAMP,
    version INTEGER,
    options_id INTEGER
        CONSTRAINT metadata_options_id_fk
            REFERENCES metadata_options
);

CREATE TABLE video (
    id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    creation_time TIMESTAMP,
    update_time TIMESTAMP,
    version INTEGER,
    location VARCHAR(255),
    name VARCHAR(255),
    selected_thumbnail INTEGER,
    library_id INTEGER
        CONSTRAINT video_library_fk
            REFERENCES library
);

CREATE TABLE thumbnail (
    id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    location VARCHAR(255),
    video_id INTEGER NOT NULL
        CONSTRAINT video_thumbnail_video_fk
            REFERENCES video
);

CREATE TABLE metadata_value (
    dtype INTEGER NOT NULL,
    id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    metadata_id INTEGER NOT NULL
        CONSTRAINT metadata_value_metadata_fk
            REFERENCES metadata,
    video_id INTEGER NOT NULL
        CONSTRAINT metadata_value_video_fk
            REFERENCES video,
    number_value INTEGER,
    string_value VARCHAR(255),
    timestamp_value TIMESTAMP,
    taglist_values VARCHAR(255) ARRAY,
    date_value DATE,
    duration_value BIGINT,
    boolean_value BOOLEAN,
    selection_value_id BIGINT
        CONSTRAINT METADATA_VALUE_SELECTION_FK
            REFERENCES selection_values,
    floating_value DOUBLE,
    time_value TIME
);

CREATE TABLE metadata_options_values (
    selection_metadata_options_id INTEGER NOT NULL
        CONSTRAINT metadata_options_metadata_fk
            REFERENCES metadata_options,
    values_id BIGINT NOT NULL UNIQUE
        CONSTRAINT metadata_options_select_fk
            REFERENCES selection_values
);

CREATE TABLE playlist (
    id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    creation_time TIMESTAMP,
    update_time TIMESTAMP,
    version INTEGER
);

CREATE TABLE playlist_videos (
    playlist_id INTEGER NOT NULL
        CONSTRAINT playlist_videos_playlist_fk
            REFERENCES playlist,
    videos_id INTEGER NOT NULL
        CONSTRAINT playlist_videos_video_fk
            REFERENCES video
);

CREATE VIEW full_metadata_value AS SELECT
       mv.dtype, mv.id, metadata_id, video_id,
       COALESCE(mv.boolean_value, mo.default_boolean_value) as boolean_value,
       COALESCE(mv.date_value, mo.default_date_value) as date_value,
--        COALESCE(mv.duration_value, mo.dura),
       COALESCE(mv.floating_value, mo.default_double_value) as floating_value,
       COALESCE(mv.number_value, mo.default_long_value) as number_value,
       COALESCE(mv.selection_value_id, mo.default_select_value_id) as selection_value_id,
       COALESCE(mv.string_value, mo.default_text_value) as string_value,
       COALESCE(mv.taglist_values, mo.default_tag_values) as taglist_values,
       COALESCE(mv.time_value, mo.default_time_value) as time_value,
       COALESCE(mv.timestamp_value, mo.default_timestamp_value) as timestamp_value
    FROM metadata_value mv
         LEFT JOIN metadata m ON mv.metadata_id = m.id
         LEFT JOIN metadata_options mo ON m.options_id = mo.id
