name: Release

on:
  push:
    tags: 
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install frontend dependencies
      run: npm ci
      working-directory: 'src/frontend'
    - name: Create jar
      run: './gradlew shadowJar'
